--- bot24-irc config
# Fill in nick, password, server, and site details with your details
credentials:
    nick: 
    authnick:
    password: 
server: irc.freenode.net
channels:
    - '#'
phabricator:
    apitoken: 
